- test/test.py
- tibber/__init__.py
>  except IndexError

- .travis.yml
- README.md
- setup.py
- test/test.py
- tibber/__init__.py
- tox.ini
Will require python 3.5 or higher
> Upgrade aiohttp

- tibber/__init__.py
On add homes with a running subscription status
> Subcription status

- .travis.yml
- tox.ini
> remove python 3.5 and 3.6

- .travis.yml
- tibber/const.py
Glitre has changed grid pricing, both winter and summer price. And made night reduction the same all year around.
> Glitre has changed grid pricing.

- README.md
- test/test.py
- tibber/__init__.py
> Remove sync_ functions

- .github/workflows/code_checker.yml
Fixes https://github.com/Danielhiversen/pyTibber/issues/178
> pytest-asyncio

- tibber/__init__.py
This PR adds the needed functions to extend the tibber component in Home Assistant to report production in the same way as consumption to be able to add it to the energy dashboard.
I tried to reuse the existing code and only generalize it to handle both consumption and production. Might be a bit messy in some places, but just let me know if you think I should change/redo something.
> Add support for getting historic/hourly production data

- tibber/tibber_home.py
> use asyncio.create_task

- tibber/__init__.py
> User agent

- tibber/tibber_home.py
> Improve error logging

- setup.py
Correct requirments, fixes #235
> Correct requirments, fixes #235

- tibber/home.py
Fixes https://github.com/Danielhiversen/pyTibber/issues/274
> Support awaiting termination

- tibber/home.py
- tibber/realtime.py
> Reconnect logic

- test/test.py
- tibber/home.py
**TL;DR: The goal of this PR is to add a new attribute to the `TibberSensorElPrice` in the HomeAssistant integration that indicates how the electricity price for the current hour compares to other hours of the current day.**
I was thinking it could be named `intraday_price_ranking`, or something similar. Naming things is hard... The implementation is a bit rough but I thought I'd ship a PR instead of opening an issue, to have something concrete to discuss.
The motivation for having an attribute like this is to be able to better plan electric use that can be postponed. For example  a water heater. I want it to run 4, 6 or maybe 8 hours a day - preferably in the cheapest hours. And that't not possible with the integration today. Looking at average prices can get you far, but not with the …
> Add intraday price rank

- .github/workflows/code_checker.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- setup.py
- test/test_tibber.py
- tibber/__init__.py
- tibber/exceptions.py
- tibber/home.py
- tibber/realtime.py
- Consolidate linting via pre-commit and ruff.
- Use pre-commit in CI to run linting.
> Improve linting

- .github/dependabot.yml
- .github/workflows/code_checker.yml
- .github/workflows/codeql.yml
- .github/workflows/python-publish.yml
- .github/workflows/rebase.yml
- Update all actions to latest versions keeping the existing version pinning strategy.
- Add dependabot config for actions.
> Update CI actions

- .github/workflows/codeql.yml
- Remove not needed autobuild step.
> Clean up codeql action

- tibber/home.py
[Solves this issue](https://github.com/home-assistant/core/issues/126607)
> Add check if lastMeterProduction is null

- test/test_tibber.py
- tibber/home.py
> Handle inactive homes
